### PR TITLE
acronym exercise

### PR DESCRIPTION
**Pull request by gabrielperales**

### CODE REVIEW

**Comment by stevejb71** [comment]
I've updated the config.json to ready the track for the V2 site. You're might need a merge. 
I'd probably mark this exercise as core: false, and unlocked by "word-count" (or perhaps phone number, which is also a string manipulation exercise)

**Comment by gabrielperales** [comment]
@stevejb71 I have rebased master, so this branch must be updated. Let me know if I have to do any other change.

**Comment by gabrielperales** [comment]
CI is broken? 🤔

**Comment by stevejb71** [comment]
The build requires an .rei file for each exercise. Having the interface makes it a bit easier for the user to start on the solution.

**Comment by tejasbubane** [comment]
I missed the `rei` file while reviewing. Also I think we should configure travis to halt on the first error and not run further build step which lead to confusing errors.

**Comment by gabrielperales** [comment]
@stevejb71 Ok! cool. I have to see its syntax and how to write one 🤣, but it seems like a good idea :)

**Comment by tejasbubane** [comment]
@gabrielperales You can look at the [reasonml docs](https://reasonml.github.io/docs/en/module.html#signatures) and [existing exercises](https://github.com/exercism/reasonml/pull/34/files). Let me know if you have any issues, happy to help :)

**Comment by gabrielperales** [comment]
@stevejb71 removed, and https://github.com/exercism/reasonml/pull/44 will help us to avoid this change request happen again

**Pull request merged**
