### PR TITLE
Integrate continuous integration

### PR DESCRIPTION
**Pull request by tejasbubane**
Configure TravisCI to build and test all exercises.

Closes: #3

### CODE REVIEW

**Comment by stevejb71** [comment]
Looks like the call to configlet is not quite right. But some useful changes which are worth merging I think

**Comment by tejasbubane** [comment]
@stevejb71 No lets not merge the incomplete thing, I will fix this today.

**Comment by kytrinyx** [comment]
The call to configlet should be `configlet lint --track-id reasonml .` (so sorry I got that wrong in the bootstrapping!)

**Comment by tejasbubane** [comment]
Alright the build is a success! @stevejb71

**Comment by stevejb71** [comment]
Awesome, that's a good step on the way to going live. 

It's also quite fast, which is nice. 

I'll merge.

**Pull request merged**
